"""
SaaS routes: registration, forgot-password, admin (users/plans/payments/settings), billing.
"""
import secrets
import shutil
from datetime import datetime, timezone, timedelta
from typing import List, Optional
from pathlib import Path

from bson import ObjectId
from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Form, Response
from fastapi.responses import FileResponse
from pydantic import BaseModel, EmailStr, Field

from core import (
    db, logger, now_iso,
    hash_password, verify_password,
    create_access_token, create_refresh_token,
    set_auth_cookies, clear_auth_cookies,
    get_current_user, require_admin, require_approved_user,
    UPLOAD_DIR, build_upi_url, qr_png_base64, gen_ref, ADMIN_EMAIL,
)

router = APIRouter(prefix="/api")

# ---------- Models ----------
class RegisterIn(BaseModel):
    email: EmailStr
    password: str = Field(min_length=6)
    name: str
    company: Optional[str] = ""
    phone: str
    alt_phone: Optional[str] = ""
    location: Optional[str] = ""

class ForgotPasswordIn(BaseModel):
    email: EmailStr

class ResetPasswordIn(BaseModel):
    token: str
    password: str = Field(min_length=6)

class PlanIn(BaseModel):
    name: str
    description: Optional[str] = ""
    price_inr: float = 0
    price_usd: float = 0
    validity_days: int = 30
    max_sessions: int = 1
    max_messages_per_day: int = 1000
    max_api_keys: int = 3
    features: List[str] = []
    active: bool = True
    sort_order: int = 0

class SettingsIn(BaseModel):
    upi_vpa: str
    upi_payee_name: str
    contact_email: Optional[str] = ""
    contact_phone: Optional[str] = ""
    invoice_note: Optional[str] = "Thank you for subscribing."
    company_name: Optional[str] = "WA_API"

class VerifyPaymentIn(BaseModel):
    admin_notes: Optional[str] = ""

class ProfileUpdateIn(BaseModel):
    name: Optional[str] = None
    company: Optional[str] = None
    phone: Optional[str] = None
    alt_phone: Optional[str] = None
    location: Optional[str] = None

class UserSuspendIn(BaseModel):
    reason: Optional[str] = ""

# ---------- Helpers ----------
def _doc_out(d):
    d = dict(d)
    d["id"] = str(d.pop("_id"))
    return d

def _user_out(u: dict) -> dict:
    u = _doc_out(u)
    u.pop("password_hash", None)
    return u

async def _get_settings() -> dict:
    doc = await db.settings.find_one({"key": "billing"})
    if not doc:
        return {"key": "billing", "upi_vpa": "", "upi_payee_name": "", "contact_email": "",
                "contact_phone": "", "invoice_note": "Thank you for subscribing.", "company_name": "WA_API"}
    doc.pop("_id", None)
    return doc

# ---------- Public: registration + forgot password ----------
@router.post("/auth/register", status_code=201)
async def register(body: RegisterIn):
    email = body.email.lower().strip()
    if await db.users.find_one({"email": email}):
        raise HTTPException(status_code=409, detail="Email already registered")
    doc = {
        "email": email,
        "password_hash": hash_password(body.password),
        "name": body.name.strip(),
        "company": body.company or "",
        "phone": body.phone.strip(),
        "alt_phone": body.alt_phone or "",
        "location": body.location or "",
        "role": "user",
        "status": "pending",  # awaits admin approval
        "current_plan_id": None,
        "subscription_expires_at": None,
        "failed_logins": 0,
        "locked_until": None,
        "created_at": now_iso(),
    }
    res = await db.users.insert_one(doc)
    logger.info("New registration: %s (%s)", email, res.inserted_id)
    return {"ok": True, "message": "Registration submitted. Awaiting admin approval."}

@router.post("/auth/forgot-password")
async def forgot_password(body: ForgotPasswordIn):
    """Creates a reset request record. Admin will generate a link from admin panel."""
    email = body.email.lower().strip()
    user = await db.users.find_one({"email": email})
    if user:
        # Create a reset request; token generated by admin at grant time
        await db.password_resets.insert_one({
            "user_id": str(user["_id"]),
            "email": email,
            "token": None,   # admin will set token
            "expires_at": None,
            "used": False,
            "requested_at": now_iso(),
            "status": "requested",
        })
    # Always return the same message to not leak email existence
    return {"ok": True, "message": "If the email exists, an admin will review your request and send you a reset link."}

@router.post("/auth/reset-password")
async def reset_password(body: ResetPasswordIn):
    doc = await db.password_resets.find_one({"token": body.token, "used": False})
    if not doc:
        raise HTTPException(status_code=400, detail="Invalid or already-used token")
    try:
        exp = datetime.fromisoformat(doc["expires_at"])
        if exp.tzinfo is None: exp = exp.replace(tzinfo=timezone.utc)
        if datetime.now(timezone.utc) >= exp:
            raise HTTPException(status_code=400, detail="Reset token expired")
    except (KeyError, ValueError, TypeError):
        raise HTTPException(status_code=400, detail="Invalid token")
    uid = doc["user_id"]
    await db.users.update_one({"_id": ObjectId(uid)},
                              {"$set": {"password_hash": hash_password(body.password),
                                        "failed_logins": 0, "locked_until": None}})
    await db.password_resets.update_one({"_id": doc["_id"]},
                                        {"$set": {"used": True, "used_at": now_iso(), "status": "used"}})
    return {"ok": True, "message": "Password reset. Please sign in."}

# ---------- Public: plans listing + settings for pricing page ----------
@router.get("/plans")
async def public_plans():
    plans = [_doc_out(p) async for p in db.plans.find({"active": True}).sort("sort_order", 1)]
    s = await _get_settings()
    return {"plans": plans, "billing": {"contact_email": s.get("contact_email"), "contact_phone": s.get("contact_phone"),
                                        "company_name": s.get("company_name")}}

# ---------- User: profile ----------
@router.put("/auth/profile")
async def update_profile(body: ProfileUpdateIn, user=Depends(get_current_user)):
    update = {k: v for k, v in body.model_dump().items() if v is not None}
    if not update:
        return {"ok": True}
    await db.users.update_one({"_id": ObjectId(user["id"])}, {"$set": update})
    u = await db.users.find_one({"_id": ObjectId(user["id"])})
    return _user_out(u)

# ---------- User: billing ----------
@router.get("/billing/summary")
async def billing_summary(user=Depends(require_approved_user)):
    """Current subscription info + plan limits + usage for regular users."""
    if user.get("role") == "admin":
        return {"is_admin": True, "unlimited": True}
    plan = None
    if user.get("current_plan_id"):
        p = await db.plans.find_one({"_id": ObjectId(user["current_plan_id"])})
        if p: plan = _doc_out(p)
    # Compute usage
    from core import today_str
    daily = await db.daily_usage.find_one({"user_id": user["id"], "date": today_str()})
    used_today = int(daily.get("messages_sent", 0)) if daily else 0
    sessions_count = await db.sessions.count_documents({"owner_id": user["id"]})
    api_keys_count = await db.api_keys.count_documents({"owner_id": user["id"], "revoked": {"$ne": True}})
    expires_at = user.get("subscription_expires_at")
    days_left = None
    if expires_at:
        try:
            exp = datetime.fromisoformat(expires_at)
            if exp.tzinfo is None: exp = exp.replace(tzinfo=timezone.utc)
            delta = (exp - datetime.now(timezone.utc)).total_seconds()
            days_left = max(0, int(delta // 86400)) if delta > 0 else 0
        except (ValueError, TypeError):
            pass
    return {
        "is_admin": False,
        "user": {"email": user["email"], "name": user.get("name"), "company": user.get("company"),
                 "status": user.get("status")},
        "plan": plan,
        "subscription_expires_at": expires_at,
        "days_left": days_left,
        "usage": {
            "messages_today": used_today,
            "sessions_count": sessions_count,
            "api_keys_count": api_keys_count,
        },
    }

@router.post("/billing/create-payment")
async def create_payment(plan_id: str = Form(...), currency: str = Form("INR"),
                         user=Depends(require_approved_user)):
    """User picks a plan → we create a pending payment and return UPI QR."""
    if user.get("role") == "admin":
        raise HTTPException(status_code=400, detail="Admin does not need to subscribe.")
    plan = await db.plans.find_one({"_id": ObjectId(plan_id), "active": True})
    if not plan:
        raise HTTPException(status_code=404, detail="Plan not found or inactive")
    currency = currency.upper()
    if currency not in ("INR", "USD"):
        raise HTTPException(status_code=400, detail="Currency must be INR or USD")
    amount = float(plan.get("price_inr", 0) if currency == "INR" else plan.get("price_usd", 0))
    settings = await _get_settings()
    vpa = settings.get("upi_vpa") or ""
    payee = settings.get("upi_payee_name") or "Admin"
    if currency == "INR" and not vpa:
        raise HTTPException(status_code=400, detail="Admin has not configured UPI VPA yet.")
    ref = gen_ref()
    upi_url = build_upi_url(vpa, payee, amount, ref, "INR") if currency == "INR" else None
    qr_data_url = qr_png_base64(upi_url) if upi_url else None

    doc = {
        "user_id": user["id"],
        "plan_id": plan_id,
        "plan_name": plan.get("name"),
        "amount": amount,
        "currency": currency,
        "upi_vpa": vpa if currency == "INR" else None,
        "upi_url": upi_url,
        "reference": ref,
        "utr_number": None,
        "screenshot_path": None,
        "status": "pending",  # pending -> submitted -> verified/rejected
        "admin_notes": "",
        "created_at": now_iso(),
        "submitted_at": None,
        "verified_at": None,
        "verified_by": None,
    }
    res = await db.payments.insert_one(doc)
    return {
        "id": str(res.inserted_id),
        "reference": ref,
        "amount": amount,
        "currency": currency,
        "upi_vpa": vpa if currency == "INR" else None,
        "upi_payee_name": payee if currency == "INR" else None,
        "upi_url": upi_url,
        "qr_data_url": qr_data_url,
        "plan_name": plan.get("name"),
        "status": "pending",
    }

@router.post("/billing/submit-utr")
async def submit_utr(payment_id: str = Form(...), utr: str = Form(...),
                     screenshot: Optional[UploadFile] = File(None),
                     user=Depends(require_approved_user)):
    p = await db.payments.find_one({"_id": ObjectId(payment_id), "user_id": user["id"]})
    if not p:
        raise HTTPException(status_code=404, detail="Payment not found")
    if p["status"] not in ("pending", "submitted"):
        raise HTTPException(status_code=400, detail=f"Payment already {p['status']}")
    update = {"utr_number": utr.strip(), "status": "submitted", "submitted_at": now_iso()}
    if screenshot is not None:
        ext = Path(screenshot.filename or "img").suffix.lower() or ".png"
        safe = f"{payment_id}{ext}"
        dest = UPLOAD_DIR / safe
        with dest.open("wb") as f:
            shutil.copyfileobj(screenshot.file, f)
        update["screenshot_path"] = safe
    await db.payments.update_one({"_id": p["_id"]}, {"$set": update})
    return {"ok": True, "message": "UTR submitted. Awaiting admin verification."}

@router.get("/billing/my-payments")
async def my_payments(user=Depends(require_approved_user)):
    items = [_doc_out(d) async for d in db.payments.find({"user_id": user["id"]}).sort("created_at", -1)]
    return {"payments": items}

# ---------- Admin: users management ----------
@router.get("/admin/users")
async def admin_list_users(_a=Depends(require_admin)):
    users = []
    async for u in db.users.find().sort("created_at", -1):
        # Attach plan name if any
        plan_name = None
        if u.get("current_plan_id"):
            p = await db.plans.find_one({"_id": ObjectId(u["current_plan_id"])})
            if p: plan_name = p.get("name")
        u = _user_out(u)
        u["plan_name"] = plan_name
        users.append(u)
    return {"users": users}

@router.post("/admin/users/{uid}/approve")
async def admin_approve_user(uid: str, _a=Depends(require_admin)):
    r = await db.users.update_one({"_id": ObjectId(uid)}, {"$set": {"status": "approved"}})
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="User not found")
    return {"ok": True}

@router.post("/admin/users/{uid}/suspend")
async def admin_suspend_user(uid: str, body: UserSuspendIn, _a=Depends(require_admin)):
    r = await db.users.update_one(
        {"_id": ObjectId(uid)},
        {"$set": {"status": "suspended", "suspend_reason": body.reason or "", "suspended_at": now_iso()}}
    )
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="User not found")
    return {"ok": True}

@router.post("/admin/users/{uid}/unsuspend")
async def admin_unsuspend_user(uid: str, _a=Depends(require_admin)):
    r = await db.users.update_one({"_id": ObjectId(uid)}, {"$set": {"status": "approved"},
                                                            "$unset": {"suspend_reason": "", "suspended_at": ""}})
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="User not found")
    return {"ok": True}

@router.delete("/admin/users/{uid}")
async def admin_delete_user(uid: str, _a=Depends(require_admin)):
    u = await db.users.find_one({"_id": ObjectId(uid)})
    if not u:
        raise HTTPException(status_code=404, detail="User not found")
    if u.get("email") == ADMIN_EMAIL:
        raise HTTPException(status_code=400, detail="Cannot delete the seed admin account.")
    # Clean up related data
    await db.sessions.delete_many({"owner_id": uid})
    await db.rules.delete_many({"owner_id": uid})
    await db.webhooks.delete_many({"owner_id": uid})
    await db.api_keys.delete_many({"owner_id": uid})
    await db.messages.delete_many({"owner_id": uid})
    await db.business_hours.delete_many({"owner_id": uid})
    await db.daily_usage.delete_many({"user_id": uid})
    await db.payments.delete_many({"user_id": uid})
    await db.password_resets.delete_many({"user_id": uid})
    await db.users.delete_one({"_id": ObjectId(uid)})
    return {"ok": True}

@router.post("/admin/users/{uid}/reset-link")
async def admin_generate_reset_link(uid: str, _a=Depends(require_admin)):
    """Admin generates a one-time password reset link. Share it with the user manually."""
    u = await db.users.find_one({"_id": ObjectId(uid)})
    if not u:
        raise HTTPException(status_code=404, detail="User not found")
    token = secrets.token_urlsafe(32)
    expires_at = (datetime.now(timezone.utc) + timedelta(hours=24)).isoformat()
    await db.password_resets.insert_one({
        "user_id": uid,
        "email": u["email"],
        "token": token,
        "expires_at": expires_at,
        "used": False,
        "created_at": now_iso(),
        "status": "granted",
        "granted_by_admin": True,
    })
    return {"ok": True, "token": token, "expires_at": expires_at,
            "reset_path": f"/reset-password?token={token}"}

@router.get("/admin/reset-requests")
async def admin_reset_requests(_a=Depends(require_admin)):
    """List pending forgot-password requests."""
    items = []
    async for d in db.password_resets.find({"status": {"$in": ["requested", "granted"]}}).sort("requested_at", -1).limit(200):
        items.append(_doc_out(d))
    return {"requests": items}

# ---------- Admin: plans CRUD ----------
@router.get("/admin/plans")
async def admin_list_plans(_a=Depends(require_admin)):
    plans = [_doc_out(p) async for p in db.plans.find().sort("sort_order", 1)]
    return {"plans": plans}

@router.post("/admin/plans", status_code=201)
async def admin_create_plan(body: PlanIn, _a=Depends(require_admin)):
    doc = body.model_dump()
    doc["created_at"] = now_iso()
    doc["updated_at"] = now_iso()
    res = await db.plans.insert_one(doc)
    doc["_id"] = res.inserted_id
    return _doc_out(doc)

@router.put("/admin/plans/{pid}")
async def admin_update_plan(pid: str, body: PlanIn, _a=Depends(require_admin)):
    upd = body.model_dump()
    upd["updated_at"] = now_iso()
    await db.plans.update_one({"_id": ObjectId(pid)}, {"$set": upd})
    p = await db.plans.find_one({"_id": ObjectId(pid)})
    if not p:
        raise HTTPException(status_code=404, detail="Not found")
    return _doc_out(p)

@router.delete("/admin/plans/{pid}")
async def admin_delete_plan(pid: str, _a=Depends(require_admin)):
    r = await db.plans.delete_one({"_id": ObjectId(pid)})
    if r.deleted_count == 0:
        raise HTTPException(status_code=404, detail="Not found")
    return {"ok": True}

# ---------- Admin: payments verification ----------
@router.get("/admin/payments")
async def admin_list_payments(status: Optional[str] = None, _a=Depends(require_admin)):
    q = {"status": status} if status else {}
    items = []
    async for p in db.payments.find(q).sort("created_at", -1).limit(500):
        u = await db.users.find_one({"_id": ObjectId(p["user_id"])}) if p.get("user_id") else None
        p = _doc_out(p)
        if u:
            p["user_email"] = u.get("email")
            p["user_name"] = u.get("name")
            p["user_company"] = u.get("company")
        items.append(p)
    return {"payments": items}

@router.get("/admin/payments/{pid}/screenshot")
async def admin_payment_screenshot(pid: str, _a=Depends(require_admin)):
    p = await db.payments.find_one({"_id": ObjectId(pid)})
    if not p or not p.get("screenshot_path"):
        raise HTTPException(status_code=404, detail="No screenshot")
    return FileResponse(UPLOAD_DIR / p["screenshot_path"])

@router.post("/admin/payments/{pid}/verify")
async def admin_verify_payment(pid: str, body: VerifyPaymentIn, admin=Depends(require_admin)):
    p = await db.payments.find_one({"_id": ObjectId(pid)})
    if not p:
        raise HTTPException(status_code=404, detail="Not found")
    if p["status"] == "verified":
        raise HTTPException(status_code=400, detail="Already verified")
    plan = await db.plans.find_one({"_id": ObjectId(p["plan_id"])})
    if not plan:
        raise HTTPException(status_code=400, detail="Plan no longer exists")
    user = await db.users.find_one({"_id": ObjectId(p["user_id"])})
    if not user:
        raise HTTPException(status_code=400, detail="User no longer exists")

    # Determine subscription start (extend if still active, else start now)
    now = datetime.now(timezone.utc)
    current_exp = user.get("subscription_expires_at")
    base = now
    if current_exp:
        try:
            ce = datetime.fromisoformat(current_exp)
            if ce.tzinfo is None: ce = ce.replace(tzinfo=timezone.utc)
            if ce > now:
                base = ce
        except (ValueError, TypeError):
            pass
    new_exp = base + timedelta(days=int(plan.get("validity_days", 30)))

    await db.users.update_one({"_id": user["_id"]}, {"$set": {
        "current_plan_id": str(plan["_id"]),
        "subscription_expires_at": new_exp.isoformat(),
        "status": "approved",  # ensure approved
    }})
    await db.payments.update_one({"_id": p["_id"]}, {"$set": {
        "status": "verified",
        "verified_at": now.isoformat(),
        "verified_by": admin["email"],
        "admin_notes": body.admin_notes or "",
        "activated_from": base.isoformat(),
        "activated_until": new_exp.isoformat(),
    }})
    return {"ok": True, "expires_at": new_exp.isoformat()}

@router.post("/admin/payments/{pid}/reject")
async def admin_reject_payment(pid: str, body: VerifyPaymentIn, admin=Depends(require_admin)):
    r = await db.payments.update_one({"_id": ObjectId(pid)}, {"$set": {
        "status": "rejected", "verified_at": now_iso(), "verified_by": admin["email"],
        "admin_notes": body.admin_notes or "",
    }})
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="Not found")
    return {"ok": True}

# ---------- Admin: settings ----------
@router.get("/admin/settings")
async def admin_get_settings(_a=Depends(require_admin)):
    return await _get_settings()

@router.put("/admin/settings")
async def admin_set_settings(body: SettingsIn, _a=Depends(require_admin)):
    data = body.model_dump()
    data["key"] = "billing"
    data["updated_at"] = now_iso()
    await db.settings.update_one({"key": "billing"}, {"$set": data}, upsert=True)
    return data

# ---------- Admin: stats overview ----------
@router.get("/admin/overview")
async def admin_overview(_a=Depends(require_admin)):
    total_users = await db.users.count_documents({"role": "user"})
    pending_users = await db.users.count_documents({"role": "user", "status": "pending"})
    suspended_users = await db.users.count_documents({"role": "user", "status": "suspended"})
    active_users = await db.users.count_documents({
        "role": "user", "status": "approved",
        "subscription_expires_at": {"$gt": now_iso()}
    })
    pending_payments = await db.payments.count_documents({"status": "submitted"})
    verified_payments = await db.payments.count_documents({"status": "verified"})
    total_plans = await db.plans.count_documents({})
    return {
        "users": {"total": total_users, "pending": pending_users, "active": active_users, "suspended": suspended_users},
        "payments": {"awaiting_verification": pending_payments, "verified": verified_payments},
        "plans_count": total_plans,
    }
